cols=c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3')
df<- read.table('household_power_consumption.txt',sep=';',na.strings='?', header = TRUE,nrows=2880, skip=66636,col.names =cols,stringsAsFactors = FALSE)
df$datetime<- paste(df$Date,df$Time)  
df$datetime<-as.POSIXct(df$datetime,format = "%d/%m/%Y %H:%M:%S")
plot(df$datetime,df$Global_active_power,type="l",xlab="",ylab="Global active power (kilowatts)")
dev.copy(png,"plot2.png",height=480, width=480)
dev.off()